### ISSUE TITLE
Allow function-calls ..

### ISSUE THREAD

**Issue by skx** [skx/marionette#108]
Looking over the various examples it seems obvious that the conditional-keys we support are nothing more than function-calls:

```
shell {
             ...
             if => equals("foo", "bar" )
             ...
}
```

So what if we generalized that?  What if we allowed:

```
let a = uppercase( "${username}" )
```

Or

```
directory { 
            target => sort( "/foo", "/foo/bar", "foo/baz/bar" ... )
}
```

Supporting this would be pretty simple __if__ we dropped the use of the `token.*` types within the parser and executor.  We'd still lex into such things, but then define some new ast-nodes:

```
ast.String{}
ast.Number{}
ast.Boolean{}
ast.Backtick{}
```

Once that was done we can define functions as:

```
type Funcall struct {
    Node
    Name string
    Args []Node
    ..
}
```

At that point we'd have a cleaner implementation:

* We'd no longer have the executor know about `token.*` values.
* We could handle all node-types easily, and identically.
* And "conditionals" would be updated to use "real" function-calls.

As a final step we could add some built-in functions which are used more generally:

* upper()
* lower()
* min(x,y)
* max(y,z)

I'm not sure what kind of primitives would make sense, but it feels like losing the token-usage in the middle of the code would be a good thing even if there were zero new additions.

## Implementation Plan

* [x] Define new AST types, return them from the parser, and use them in the executor.
  * This will result in zero functional changes.
* [x] Update conditional values to be function-calls.
  * This will result in zero functional changes.
  * As `if` and `unless` are the only places where function-calls are supported.  If their implementation changes nobody will notice.
* [x] Finally define a few new functions which can be used for assignments, values, etc.
   * This will be the first time the new feature is exposed.

It is important to note that I don't want a whole new programming language, nor do I see adding more than 10-20 primitive functions.  Too much complexity would spoil things, but we could definitely add `trim` and similar utility methods which would be useful.
